### ISSUE TITLE
About Tensorflow version

### ISSUE THREAD

**Issue by lakomi** [pasquini-dario/PLR#10]
I have two problem.
1、What is your version of TensorFlow、CUDA and cudnn?
2、 Do you have code with PyTorch? Or, Can you provide the code for TensorFlow2.x？

**Comment by pasquini-dario** [comment]
Hello,

1. As I wrote in the readme, the version is: tf 1.14.0. I can't recall the exact versions of cuDNN and CUDA I used when I ran the experiments. However, this [table](https://www.tensorflow.org/install/source#gpu) lists everything you need to know about tf's compatibility.
2.  Sorry, there is no PyTorch code available and, at the moment, I'm not plaining to write a tf2 version for this code.

**Comment by lakomi** [comment]
> Hello,
> 
> 1. As I wrote in the readme, the version is: tf 1.14.0. I can't recall the exact versions of cuDNN and CUDA I used when I ran the experiments. However, this [table](https://www.tensorflow.org/install/source#gpu) lists everything you need to know about tf's compatibility.
> 2. Sorry, there is no PyTorch code available and, at the moment, I'm not plaining to write a tf2 version for this code.


Hello, have you ever had this problem？This problem occurs when I execute “python train.py CONF/arch1.gin”。
tensorflow 1.15.0。my tensorflow_hub is 0.11.0,but it requires tensorflow >=1.15.0。

Traceback (most recent call last):
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(64, 128), b.shape=(128, 1280), m=64, n=1280, k=128
         [[{{node arch1.gin/G/dense/MatMul}}]]
  (1) Internal: Blas GEMM launch failed : a.shape=(64, 128), b.shape=(128, 1280), m=64, n=1280, k=128
         [[{{node arch1.gin/G/dense/MatMul}}]]
         [[arch1.gin/add_2/_25]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 132, in <module>
    main()
  File "train.py", line 125, in main
    pg.train(data, epochs, batch_size, summary_steps_number=100, use_tqdm=True)
  File "/home/qss/python_project/PLR/PasswordGAN/vanilla.py", line 97, in train
    summary = sess.run(merged)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(64, 128), b.shape=(128, 1280), m=64, n=1280, k=128
         [[node arch1.gin/G/dense/MatMul (defined at /home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Internal: Blas GEMM launch failed : a.shape=(64, 128), b.shape=(128, 1280), m=64, n=1280, k=128
         [[node arch1.gin/G/dense/MatMul (defined at /home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[arch1.gin/add_2/_25]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'arch1.gin/G/dense/MatMul':
  File "train.py", line 132, in <module>
    main()
  File "train.py", line 125, in main
    pg.train(data, epochs, batch_size, summary_steps_number=100, use_tqdm=True)
  File "/home/qss/python_project/PLR/PasswordGAN/vanilla.py", line 69, in train
    gen_train_op, disc_train_op = self.model_function(TRAIN, self.hparams, constants_tf, **data_tf)
  File "/home/qss/python_project/PLR/PasswordGAN/FAIL/rawModel.py", line 119, in model_function
    y_ = self.build_model(mode, params, constants=constants, **kargs)
  File "/home/qss/python_project/PLR/PasswordGAN/vanilla.py", line 151, in build_model
    G = G_maker(z, x_size, dict_size, is_training=is_training)
  File "/home/qss/python_project/PLR/PasswordGAN/architectures.py", line 98, in G1
    x = tf.layers.dense(x, layer_dim * seq_len)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py", line 187, in dense
    return layer.apply(inputs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 234, in wrapper
    return converted_call(f, options, args, kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 439, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 330, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/core.py", line 1050, in call
    outputs = gen_math_ops.mat_mul(inputs, self.kernel)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 6136, in mat_mul
    name=name)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/qss/miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
