### ISSUE TITLE
the version of tensdflow_hub

### ISSUE THREAD

**Issue by kmcrystal** [pasquini-dario/PLR#8]
The website https://www.tensorflow.org/hub/installation writes: TensorFlow 1.15 TensorFlow 1.x is still subject to tensorflow_hubthe sole repository (starting from version 0.11.0) support. 
but
The author wrote in the environmental requirements that it was tested in tensorflow 1.14，and when there is tensorflow_hub.
i cant understand.
and
When I use tensorflow_hub0.12.0 and tensorflow1.15.0, an error is reported

Traceback (most recent call last):
  File "generatePasswords.py", line 35, in <module>
    x = passgan(z, signature=MHUB_SIGNATURE)
  File "/home/hello/miniconda3/envs/tensflow/lib/python3.6/site-packages/tensorflow_hub/module.py", line 260, in __call__
    input_tensor_infos = self._spec.get_input_info_dict(signature, self._tags)
  File "/home/hello/miniconda3/envs/tensflow/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 366, in get_input_info_dict
    signature_def = self._get_signature_def(signature, tags)
  File "/home/hello/miniconda3/envs/tensflow/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 379, in _get_signature_def
    raise ValueError("Signature %r is missing from meta graph." % signature)
ValueError: Signature 'latent_to_data' is missing from meta graph.

It seems that the parameter latent_to_data is not declared in the tensorflow_hub library. Is it a version issue?
I hope you can help to answer when you are free, thank you.

**Comment by xtfan** [comment]
tensorflow 1.14 and tensorflow_hub 0.8.0 work for me

**Comment by linsonandrew** [comment]
> The website https://www.tensorflow.org/hub/installation writes: TensorFlow 1.15 TensorFlow 1.x is still subject to tensorflow_hubthe sole repository (starting from version 0.11.0) support. but The author wrote in the environmental requirements that it was tested in tensorflow 1.14，and when there is tensorflow_hub. i cant understand. and When I use tensorflow_hub0.12.0 and tensorflow1.15.0, an error is reported
> 
> Traceback (most recent call last): File "generatePasswords.py", line 35, in x = passgan(z, signature=MHUB_SIGNATURE) File "/home/hello/miniconda3/envs/tensflow/lib/python3.6/site-packages/tensorflow_hub/module.py", line 260, in **call** input_tensor_infos = self._spec.get_input_info_dict(signature, self._tags) File "/home/hello/miniconda3/envs/tensflow/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 366, in get_input_info_dict signature_def = self._get_signature_def(signature, tags) File "/home/hello/miniconda3/envs/tensflow/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 379, in _get_signature_def raise ValueError("Signature %r is missing from meta graph." % signature) ValueError: Signature 'latent_to_data' is missing from meta graph.
> 
> It seems that the parameter latent_to_data is not declared in the tensorflow_hub library. Is it a version issue? I hope you can help to answer when you are free, thank you.





where you able to run this repo since i am facing the same issue :(
